package org.example.cache;

import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.*;
import org.example.SQLiteLexer;
import org.example.SQLiteParser;
import org.example.QueryNormalizer;
import org.example.model.CacheResult;
import java.util.concurrent.ConcurrentHashMap;
import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class QueryPlanCache {
    private final Map<String, String> cache = new ConcurrentHashMap<>();
    private final AtomicInteger hits = new AtomicInteger(0);
    private final AtomicInteger misses = new AtomicInteger(0);
    private Connection connection;

    public QueryPlanCache() {
        try {
            // Connect to the downloaded Northwind SQLite database
            this.connection = DriverManager.getConnection("jdbc:sqlite:northwind.db");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public CacheResult getPlan(String sql) {
        long startTime = System.nanoTime();

        SQLiteLexer lexer = new SQLiteLexer(CharStreams.fromString(sql));
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        SQLiteParser parser = new SQLiteParser(tokens);
        ParseTree tree = parser.parse();

        ParseTreeWalker walker = new ParseTreeWalker();
        QueryNormalizer normalizer = new QueryNormalizer();
        walker.walk(normalizer, tree);
        String key = normalizer.getNormalizedSql();

        boolean isHit = cache.containsKey(key);
        String plan;

        if (isHit) {
            hits.incrementAndGet();
            plan = cache.get(key);
        } else {
            misses.incrementAndGet();
            String operation = key.split(" ")[0].toUpperCase(); 
            
            String strategy = "Optimal Index Scan";
            
            // Generate real EXPLAIN QUERY PLAN using SQLite
            if (connection != null && operation.equals("SELECT")) {
                try (Statement stmt = connection.createStatement()) {
                    // SQLite EXPLAIN QUERY PLAN returns details about how it will execute
                    ResultSet rs = stmt.executeQuery("EXPLAIN QUERY PLAN " + key);
                    StringBuilder strategyBuilder = new StringBuilder();
                    while (rs.next()) {
                        strategyBuilder.append(rs.getString("detail")).append(" | ");
                    }
                    if (strategyBuilder.length() > 0) {
                        strategy = strategyBuilder.toString();
                        // remove trailing " | "
                        strategy = strategy.substring(0, strategy.length() - 3);
                    } else {
                        strategy = "No execution plan generated by DB";
                    }
                } catch (SQLException e) {
                    strategy = "Error generating plan: " + e.getMessage();
                }
            } else if (!operation.equals("SELECT")) {
                strategy = "Execution Plan for " + operation;
            }

            // Escape JSON strings
            strategy = strategy.replace("\"", "\\\"");

            plan = "{\n" +
                   "  \"execution_plan\": {\n" +
                   "    \"operation\": \"" + operation + "\",\n" +
                   "    \"strategy\": \"" + strategy + "\",\n" +
                   "    \"rows_estimated\": 100\n" +
                   "  }\n" +
                   "}";
            cache.put(key, plan);
        }

        long endTime = System.nanoTime();
        long executionTimeMs = (endTime - startTime) / 1000000;
        
        return new CacheResult(plan, normalizer.getParameters(), isHit, executionTimeMs);
    }

    public void clearCache() {
        cache.clear();
        hits.set(0);
        misses.set(0);
    }

    public Map<String, Integer> getStats() {
        return Map.of("hits", hits.get(), "misses", misses.get());
    }

    public Map<String, String> getCacheDump() {
        return cache;
    }
}
